# Add to plugins: list
plugins:
  - jekyll-remote-theme

# set up remote_theme
remote_theme: jekyll/minima

minima:
  skin: dark
  data_format: "%b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/zabimaruu" }